name: todo_prioritizer
description: made by ju

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  fading_edge_scrollview: ^1.1.4
  dropdown_formfield: ^0.1.3

  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.6
  firebase_analytics: ^5.0.6

  animations: ^1.1.2
  animated_splash: ^1.0.0
  flutter_focus_watcher: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

  assets:
     - images/profile/


  fonts:
   - family: Roboto
     fonts:
       - asset: fonts/roboto/Roboto-Thin.ttf
         weight: 300

       - asset: fonts/roboto/Roboto-Medium.ttf
         weight: 400

       - asset: fonts/roboto/Roboto-Regular.ttf

       - asset: fonts/roboto/Roboto-Italic.ttf
         style: italic

       - asset: fonts/roboto/Roboto-Bold.ttf
         weight: 700

       - asset: fonts/roboto/Roboto-BoldItalic.ttf
         weight: 700
         style: italic

       - asset: fonts/roboto/Roboto-Black.ttf
         weight: 900




